### ISSUE TITLE
Switch between Solidity <-> Yul automatically 

### ISSUE THREAD

**Issue by pokrovskyy** [ethereum/remix-project#2777] opened 2022-08-17 16:23 UTC
Feature request - it's annoying to go every time to Compiler Configuration and manually switch between Solidity and Yul when working on contracts targeting these two languages. I think it would make perfect sense to automatically switch the compiler selection to whatever file type is currently opened (Solidity for `.sol`, Yul for `.yul`)

**Comment by Aniket-Engg** [comment] 2022-08-18 05:44
Duplicate of https://github.com/ethereum/remix-project/issues/2692

**Closed** 2023-02-14 14:05 UTC
