### ISSUE TITLE
file explorer is not loading

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#4298] opened 2023-12-04 02:25 UTC
I've tried a few times on Chrome and on Firefox.  

I just get the spinner:
<img width="473" alt="image" src="https://github.com/ethereum/remix-project/assets/6050001/046a302e-63fb-4100-a54c-5b2faf8c7a79">

But with incognito window it loads.

**Comment by ryestew** [comment] 2023-12-07 18:01
It is not for me and for me it is a big issue.  Only on Chrome

**Comment by 0x0elliot** [comment] 2023-12-27 14:25
works fine for me and i use chrome. do you think it's a weird caching issue? do you spot any errors in your console?

**Comment by joeizang** [comment] 2024-03-25 14:00
I cannot reproduce this bug so I will close it. @ryestew you can reopen it if it still exists.

**Closed by joeizang** 2024-03-25 14:00 UTC
Labels: bug
