### ISSUE TITLE
Cannot highlight and copy

### ISSUE THREAD

**Issue by REGO350** [ethereum/remix-project#1819] opened 2021-12-01 06:10 UTC
I used to be able to highlight and copy call result, but I can't on the new remix (broswer version).

<img width="358" alt="Screen Shot 2021-12-01 at 15 05 51" src="https://user-images.githubusercontent.com/62818999/144181268-5837488d-efd8-4398-8705-b6f9705d0f29.png">

**Comment by LianaHus** [comment] 2021-12-06 11:14
@REGO350 I'm soryy I can't reproduce this. double click on value is selecting it for me. Or maybe I got it wrong? Can you please add more details

**Comment by REGO350** [comment] 2021-12-06 11:20
Oh, I have to _double click_ to highlight. Because I used to be able to click and drag over the text to highlight.

**Comment by ioedeveloper** [comment] 2022-01-18 11:30
This is fixed now by move to react https://github.com/ethereum/remix-project/pull/1850

**Closed by ioedeveloper** 2022-01-18 11:30 UTC
Labels: bug
