### ISSUE TITLE
UI bug on saved contracts warning & Saved Contracts title

### ISSUE THREAD

**Issue by ryestew** [ethereum/remix-project#4582] opened 2024-02-28 00:21 UTC
- [ ] When you save a contract, it goes to the Saved Contract section.  And if there are no other contracts in the Deployed Contracts section then the warning comes up that says:
<img width="300" alt="image" src="https://github.com/ethereum/remix-project/assets/6050001/af7ea770-45f8-4362-921f-134d4bea498c">

But I do have a contract to interact with - I just deployed it and saved it.

- [ ] Also Saved Contracts are Deployed Contracts - so we need to do a bit of renaming.  
I was thinking of Freshly Deployed Contracts - but this isn't right.  I'll put some ideas here later.

- [ ] when you change to the RemixVM and then switch back to injected provider, the saved contracts do not reappear -unless you refresh Remix.

**Comment by Aniket-Engg** [comment] 2024-02-28 08:58
@ryestew I cannot reproduce 3rd point. Its working fine for me.

**Comment by Aniket-Engg** [comment] 2024-02-29 08:45
For second point, may be we can categorize as pinned and unpinned contracts

**Comment by Aniket-Engg** [comment] 2024-03-18 08:19
fixed by https://github.com/ethereum/remix-project/pull/4600

**Closed by Aniket-Engg** 2024-03-18 08:19 UTC
Labels: UX
