### ISSUE TITLE
Changing environments does not properly reset JavaScript VM state

### ISSUE THREAD

**Issue by nicexe** [ethereum/remix-project#1438] opened 2021-08-04 08:10 UTC
I am having an issue with remix when it comes to changing environments.
Here is a high-level description on how to reproduce:

1. Make sure you have JavaScript VM (Berlin) as your active environment in the Deploy & run transactions pane.
2. Compile and deploy smart contract A.
3. Interact with smart contract A and verify that the output matches the expected behavior of the smart contract's source code.
4. Change the active environment to JavaScript VM (London) and then back to JavaScript VM (Berlin) to reset the state of the environment.
5. Make changes to smart contract A (lets call it A`).
6. Compile and deploy smart contract A`.
7. Interact with smart contract A` and verify that the output matches the expected behavior of the smart contract's source code.

On the last step, I'm getting the behavior of A instead of A`. It is as if the old bytecode remains when trying to deploy at the same address or the old bytecode is used when deploying.

**Comment by Aniket-Engg** [comment] 2021-08-06 07:47
Thanks for raising this @nicexe .

I couldn't reproduce it on remix live. I tried by adding an extra event on method call and tx details in remix terminal shows that. So for me it works fine after compilation.  Make sure you compile the contract (A`) after making changes to it.

If you still get the issue, please add more details to reproduce it.

**Comment by Aniket-Engg** [comment] 2021-08-17 13:49
Closing it. Feel free to reopen if issue persists.

**Comment by Aniket-Engg** [comment] 2021-08-17 13:49
Closing it. Feel free to reopen if issue persists.

**Closed by Aniket-Engg** 2021-08-17 13:49 UTC
