### ISSUE TITLE
UI Broken when running test case - Model is disposed

### ISSUE THREAD

**Issue by fyhao** [ethereum/remix-project#2049] opened 2022-02-06 10:49 UTC
UI Broken when running test case - Model is disposed. Issue can be repeatable by refresh browser, select a script, run a test, the script editor will be blank out and dev console can see Model is disposed error.

![image](https://user-images.githubusercontent.com/1223477/152677273-cb40d393-80da-4cab-a680-1ea36dc30914.png)

**Comment by Aniket-Engg** [comment] 2022-02-07 08:12
@fyhao I couldn't reproduce it at my end with mentioned steps. Let me know if I am missing something.

**Comment by fyhao** [comment] 2022-02-07 08:22
HI there, 

I was just learning and used below sample code

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/utils/Counters.sol";

contract EmotionalShapes is ERC721 {
    using Counters for Counters.Counter;
    Counters.Counter private _tokenIdCounter;

    constructor() ERC721("EmotionalShapes", "ESS") {}

    function _baseURI() internal pure override returns (string memory) {
        return "YOUR_API_URL/api/erc721/";
    }

    function mint(address to)
        public returns (uint256)
    {
        require(_tokenIdCounter.current() < 3); 
        _tokenIdCounter.increment();
        _safeMint(to, _tokenIdCounter.current());

        return _tokenIdCounter.current();
    }
}
```

and generated unit test script

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/utils/Counters.sol";

contract EmotionalShapes is ERC721 {
    using Counters for Counters.Counter;
    Counters.Counter private _tokenIdCounter;

    constructor() ERC721("EmotionalShapes", "ESS") {}

    function _baseURI() internal pure override returns (string memory) {
        return "YOUR_API_URL/api/erc721/";
    }

    function mint(address to)
        public returns (uint256)
    {
        require(_tokenIdCounter.current() < 3); 
        _tokenIdCounter.increment();
        _safeMint(to, _tokenIdCounter.current());

        return _tokenIdCounter.current();
    }
}
```

I was able to simulate quite many times in official website.

Then I tried to fork this project and try to run locally, was able to simulate once as well.

But after that strangely no matter how I test I can't simulate in my local env and also official website already.

Noticed that there is Transaction has been reverted error in solidity level after executing transferFrom function, but sometimes google chrome console will show javascript error on Transaction related followed by Model is disposed error. But now, it seem will still show Transaction error on solidity level but no longer show transaction error nor model is disposed error on Chrome console anymore and Editor is not hanged anymore.

Not able to simulate now.

**Comment by Aniket-Engg** [comment] 2022-02-07 10:49
Hmmm, ok. I am closing it as of now. You can reopen it if you can reproduce the issue again. Thanks for your inputs.

**Closed by Aniket-Engg** 2022-02-07 10:49 UTC

**Comment by tejin3** [comment] 2022-02-25 09:01
![001](https://user-images.githubusercontent.com/86044250/155686327-7e49d465-f853-46b5-aa0a-bf7696640684.PNG)
i have same err

**Comment by tejin3** [comment] 2022-02-25 09:03
![002](https://user-images.githubusercontent.com/86044250/155686668-af86047a-5d04-4d6e-b3f3-81691b0837be.png)
i have same err
